export const INDIAN_CAR_BRANDS = [
  "Maruti Suzuki",
  "Hyundai",
  "Tata Motors",
  "Mahindra",
  "Kia",
  "Toyota",
  "Honda",
  "Volkswagen",
  "Skoda",
  "Ford",
  "MG Motor",
  "Renault",
  "Nissan",
  "Citroën",
  "Jeep",
  "BMW",
  "Mercedes-Benz",
  "Audi",
  "Chevrolet",
  "Fiat",
  "Datsun",
];

export const BRAND_MODELS: Record<string, string[]> = {
  "Maruti Suzuki": [
    "Swift",
    "Baleno",
    "Brezza",
    "Dzire",
    "Ertiga",
    "WagonR",
    "Alto",
    "Alto K10",
    "Celerio",
    "Celerio X",
    "Eeco",
    "Fronx",
    "Grand Vitara",
    "Jimny",
    "Ciaz",
    "XL6",
    "Ignis",
    "S-Presso",
    "Ritz",
    "Omni",
    "800",
    "Zen",
    "Estilo",
    "SX4",
    "A-Star",
    "S-Cross",
    "Gypsy",
  ],
  Hyundai: [
    "Creta",
    "Venue",
    "i20",
    "Grand i10",
    "Grand i10 Nios",
    "i10",
    "Santro",
    "Santro Xing",
    "Verna",
    "Exter",
    "Aura",
    "Eon",
    "Alcazar",
    "Tucson",
    "Elantra",
    "Accent",
    "Getz",
    "Ioniq 5",
  ],
  "Tata Motors": [
    "Nexon",
    "Punch",
    "Harrier",
    "Safari",
    "Safari Storme",
    "Altroz",
    "Tiago",
    "Tigor",
    "Indica",
    "Indigo",
    "Indigo Manza",
    "Sumo",
    "Hexa",
    "Nano",
    "Zest",
    "Curvv",
  ],
  Mahindra: [
    "Thar",
    "XUV700",
    "Scorpio",
    "Scorpio-N",
    "Scorpio Classic",
    "XUV300",
    "XUV500",
    "XUV400",
    "Bolero",
    "Bolero Neo",
    "Xylo",
    "TUV300",
    "KUV100",
    "Verito",
    "Marazzo",
  ],
  Kia: ["Seltos", "Sonet", "Carens", "EV6", "Carnival"],
  Toyota: [
    "Fortuner",
    "Innova",
    "Innova Crysta",
    "Innova Hycross",
    "Glanza",
    "Etios",
    "Etios Liva",
    "Etios Cross",
    "Urban Cruiser",
    "Urban Cruiser Taisor",
    "Corolla Altis",
    "Qualis",
    "Yaris",
    "Hilux",
    "Camry",
    "Land Cruiser",
  ],
  Ford: [
    "EcoSport",
    "Figo",
    "Endeavour",
    "Aspire",
    "Fiesta",
    "Freestyle",
    "Ikon",
  ],
  Honda: ["City", "Elevate", "Amaze", "Civic", "Jazz", "WR-V", "CR-V", "Brio"],
  Volkswagen: ["Polo", "Vento", "Virtus", "Taigun", "Tiguan", "Ameo", "Jetta"],
  Skoda: ["Rapid", "Slavia", "Kushaq", "Kodiaq", "Octavia", "Superb", "Fabia"],
  "MG Motor": ["Hector", "Astor", "ZSEV", "Comet EV", "Gloster"],
  Renault: ["Duster", "Kiger", "Triber", "Kwid", "Lodgy", "Pulse"],
  Nissan: ["Magnite", "Terrano", "Micra", "Sunny"],
  Citroën: ["C3", "C3 Aircross", "eC3", "C5 Aircross", "Basalt"],
  Jeep: ["Compass", "Meridian", "Wrangler"],
  BMW: ["3 Series", "5 Series", "X1", "X3", "X5", "7 Series", "M3", "M5"],
  "Mercedes-Benz": [
    "C-Class",
    "E-Class",
    "S-Class",
    "GLA",
    "GLC",
    "GLE",
    "GLS",
  ],
  Audi: ["A4", "A6", "Q3", "Q5", "Q7", "e-tron"],
  Chevrolet: ["Beat", "Cruze", "Spark", "Tavera", "Sail"],
  Fiat: ["Punto", "Linea", "Avventura", "Palio"],
  Datsun: ["GO", "GO+", "redi-GO"],
};

// 2. Refined High-Fidelity UI Option Lists
export const FUEL_TYPE_OPTIONS = [
  { value: "petrol", label: "Petrol" },
  { value: "diesel", label: "Diesel" },
  { value: "cng", label: "CNG" },
  { value: "electric", label: "Electric (EV)" },
  { value: "hybrid", label: "Petrol Hybrid" },
];

export const TRANSMISSION_OPTIONS = [
  { value: "manual", label: "Manual (M/T)" },
  { value: "automatic", label: "Automatic (A/T)" },
];
